/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as BackofficeNewRouteImport } from './routes/backoffice/new'
import { Route as BackofficeLoginRouteImport } from './routes/backoffice/login'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as BackofficeEditIdRouteImport } from './routes/backoffice/edit.$id'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/backoffice/',
  path: '/backoffice/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeNewRoute = BackofficeNewRouteImport.update({
  id: '/backoffice/new',
  path: '/backoffice/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeLoginRoute = BackofficeLoginRouteImport.update({
  id: '/backoffice/login',
  path: '/backoffice/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeEditIdRoute = BackofficeEditIdRouteImport.update({
  id: '/backoffice/edit/$id',
  path: '/backoffice/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/api/health': typeof ApiHealthRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/new': typeof BackofficeNewRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/backoffice/edit/$id': typeof BackofficeEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/api/health': typeof ApiHealthRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/new': typeof BackofficeNewRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/backoffice/edit/$id': typeof BackofficeEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/api/health': typeof ApiHealthRoute
  '/backoffice/login': typeof BackofficeLoginRoute
  '/backoffice/new': typeof BackofficeNewRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/backoffice/edit/$id': typeof BackofficeEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/submit'
    | '/api/health'
    | '/backoffice/login'
    | '/backoffice/new'
    | '/backoffice'
    | '/backoffice/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/submit'
    | '/api/health'
    | '/backoffice/login'
    | '/backoffice/new'
    | '/backoffice'
    | '/backoffice/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/submit'
    | '/api/health'
    | '/backoffice/login'
    | '/backoffice/new'
    | '/backoffice/'
    | '/backoffice/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SubmitRoute: typeof SubmitRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BackofficeLoginRoute: typeof BackofficeLoginRoute
  BackofficeNewRoute: typeof BackofficeNewRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
  BackofficeEditIdRoute: typeof BackofficeEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/new': {
      id: '/backoffice/new'
      path: '/backoffice/new'
      fullPath: '/backoffice/new'
      preLoaderRoute: typeof BackofficeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/login': {
      id: '/backoffice/login'
      path: '/backoffice/login'
      fullPath: '/backoffice/login'
      preLoaderRoute: typeof BackofficeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice/edit/$id': {
      id: '/backoffice/edit/$id'
      path: '/backoffice/edit/$id'
      fullPath: '/backoffice/edit/$id'
      preLoaderRoute: typeof BackofficeEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SubmitRoute: SubmitRoute,
  ApiHealthRoute: ApiHealthRoute,
  BackofficeLoginRoute: BackofficeLoginRoute,
  BackofficeNewRoute: BackofficeNewRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
  BackofficeEditIdRoute: BackofficeEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
